### ISSUE TITLE
`master` branch currently fails to build

### ISSUE THREAD

**Issue by SeaMonkey82** [Consensys/web3signer#1004]
`1b6613322da023c6d6955b5abf2261c89dee8488`
```
FAILURE: Build failed with an exception.

* Where:
Build file '/home/seamonkey/Downloads/holesky/web3signer/build.gradle' line: 95

* What went wrong:
A problem occurred evaluating root project 'web3signer'.
> Could not open dsl generic class cache for script '/home/seamonkey/Downloads/holesky/web3signer/gradle/versions.gradle' (/home/seamonkey/.gradle/caches/7.6/scripts/958v0bkjul7ubaku6phsepg1z).
   > BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 65
```

**Comment by usmansaleem** [comment]
@SeaMonkey82 looks like JVM issue, can you make sure you are using JDK 17? We are in process of upgrading to JDK 21 (there is a PR open for it).

**Comment by SeaMonkey82** [comment]
Thanks.  Recently installed `openjdk-21-jdk` because something else requires it.  `sudo update-java-alternatives --set java-1.17.0-openjdk-amd64` to build and `sudo update-java-alternatives --set java-1.21.0-openjdk-amd64` did the trick.

**Comment by usmansaleem** [comment]
Glad it sorted out, feel free to reopen the issue if you have further queries.
