### ISSUE TITLE
JWT permissioned access to APIs

### ISSUE THREAD

**Issue by jframe** [ConsenSys/web3signer#128]
Restrict access to APIs based access permissions from a JWT on the request.

Acceptance Criteria
* Allow configuration of JWT public key used for verification of the JWT
* Deny access to APIs that don't have a JWT
* Add role based authentication to APIs based on FC access permissions. FC defines 4 roles read, write, sign and admin.

**Comment by arash009** [comment]
Closing this as "Not Done" for now. Will revisit if required.
