### ISSUE TITLE
FC new key API

### ISSUE THREAD

**Issue by jframe** [ConsenSys/web3signer#135]
Add support for FC WalletNew RPC which creates a new private key stores it and returns the public key. This works for either BLS or secp keys.

The API details are defined here https://github.com/filecoin-project/lotus/blob/master/api/api_full.go#L160

The param is a number indicating 2 for BLS or 1 for secp256k1 keys. And the result is a either the BLS FC address or the secp256k1 FC address.

Example request:
{ "jsonrpc": "2.0", "method": "Filecoin.WalletNew", "params": [ 2 ], "id": 3 }

response:
{"jsonrpc":"2.0","result":"t3uvfi2ayioq4v72rapj7ynlpg7ily6ttibjaq6uohmleq7lwrosgymjequu6q6mvxsj5toajha65k2k5d7f7a","id":3}

**Comment by tzapu** [comment]
would this work for an eth2 bls key as well?

**Comment by jframe** [comment]
This will create a standard BLS key and that key can be used from any of the APIs that interact with keys including the existing rest signing API that is used for eth2 signing. We also are planing on adding rest APIs for creating keys at a later stage.

**Comment by arash009** [comment]
Closing this as "Not Done" for now. Will revisit if required.
