### ISSUE TITLE
FC Key export

### ISSUE THREAD

**Issue by jframe** [ConsenSys/web3signer#139]
Add support for FC WalletExport RPC which exports a private key.

The API details are defined here https://github.com/filecoin-project/lotus/blob/master/api/api_full.go#L179

There are is one argument the filecoin address to be exported. The result is a KeyInfo struct https://github.com/filecoin-project/lotus/blob/master/chain/types/keystore.go#L13

Example request:
{ "jsonrpc": "2.0", "method": "Filecoin.WalletExport", "params": ["t3udmivibpkn7fgfc5heyz3znivubf5slvxvtiry3cwwqbvojlfikr56u34madf6ssvuwdo6btzpmm2is7rriq"], "id": 3 }

response:
{"jsonrpc":"2.0","result":{"Type":"bls","PrivateKey":"uS5CNfdkduBQ1c3ts3eTt7OAcNyDREnppaM8qY1fkxE="},"id":3}

**Comment by arash009** [comment]
Closing this as "Not Done" for now. Will revisit if required.
