### ISSUE TITLE
FC key delete API

### ISSUE THREAD

**Issue by jframe** [ConsenSys/web3signer#141]
Add support for FC WalletDelete RPC which deletes a key.

The API details are defined here https://github.com/filecoin-project/lotus/blob/master/api/api_full.go#L183

There are is one argument the filecoin address of the key to be deleted.

Example request:
{ "jsonrpc": "2.0", "method": "Filecoin.WalletDelete", "params": ["t3uvfi2ayioq4v72rapj7ynlpg7ily6ttibjaq6uohmleq7lwrosgymjequu6q6mvxsj5toajha65k2k5d7f7a"], "id": 3 }

response:
{"jsonrpc":"2.0","id":3}

**Comment by arash009** [comment]
Closing this as "Not Done" for now. Will revisit if required.
