### ISSUE TITLE
YubiHSM device password required when starting Web3Signer

### ISSUE THREAD

**Issue by bgravenorst** [ConsenSys/web3signer#258]
The YubiHSM device password is currently set in the key config file. However, when running Web3Signer using the following:

`~/web3signer/build/distributions/web3signer-0.1.1-SNAPSHOT/bin/web3signer --key-store-path=<blah> --logging=TRACE eth2`

I'm prompted to reenter the password on the command line. Additionally, the private key is displayed in the trace output. The private key should probably be hidden.

**Comment by usmansaleem** [comment]
This particular implementation of YubiHSM integration (via yubihsm-shell) has been removed from web3signer. An upcoming PR will integrate YubiHSM via PKCS11 module.
