### ISSUE TITLE
Integrate updated Yubihsm (via Signers) with Web3Signer

### ISSUE THREAD

**Issue by usmansaleem** [ConsenSys/web3signer#280]
Integration updated YubiHSM with Web3Signer.

**Sample meta file**

Connector url can either be http or yhusb

http connector:
`http://localhost:12345`

usb connector:
`yhusb://` (will pick first YubiHSM automatically)
`yhusb://serial=111222333` (Using serial number)

additionalInitConfig: _The additional init config can be obtained from https://developers.yubico.com/YubiHSM2/Component_Reference/PKCS_11/. They have to be specified as a space separated string._

~~~
type: yubihsm
pkcs11ModulePath: /path/to/yubihsm-sdk/lib/pkcs11/yubihsm_pkcs11.so
connectorUrl: yhusb://
additionalInitConfig: debug libdebug timeout=5
authId: 1
password: test
opaqueDataId: 1
keyType: BLS
~~~

**Comment by usmansaleem** [comment]
Notes:
Test data creation

`
  ./yubihsm-shell --connector=yhusb:// --authkey=1 --password=password \
   --action=put-opaque \
   --object-id=1 --domains=1 \
   --algorithm=opaque-data --capabilities=none \
   --informat=hex --in=000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f

   ./yubihsm-shell --connector=yhusb:// --authkey=1 --password=password \
   --action=put-opaque \
   --object-id=2 --domains=1 \
   --algorithm=opaque-data --capabilities=none \
   --informat=hex --in=73d51abbd89cb8196f0efb6892f94d68fccc2c35f0b84609e5f12c55dd85aba8

   ./yubihsm-shell --connector=yhusb:// --authkey=1 --password=password \
   --action=put-opaque \
   --object-id=3 --domains=1 \
   --algorithm=opaque-data --capabilities=none \
   --informat=hex --in=39722cbbf8b91a4b9045c5e6175f1001eac32f7fcd5eccda5c6e62fc4e638508

   ./yubihsm-shell --connector=yhusb:// --authkey=1 --password=password \
   --action=put-opaque \
   --object-id=4 --domains=1 \
   --algorithm=opaque-data --capabilities=none \
   --informat=hex --in=4c9326bb9805fa8f85882c12eae724cef0c62e118427f5948aefa5c428c43c93

   ./yubihsm-shell --connector=yhusb:// --authkey=1 --password=password \
   --action=put-opaque \
   --object-id=5 --domains=1 \
   --algorithm=opaque-data --capabilities=none \
   --informat=hex --in=384a62688ee1d9a01c9d58e303f2b3c9bc1885e8131565386f75f7ae6ca8d147

   ./yubihsm-shell --connector=yhusb:// --authkey=1 --password=password \
   --action=put-opaque \
   --object-id=6 --domains=1 \
   --algorithm=opaque-data --capabilities=none \
   --informat=hex --in=4b6b5c682f2db7e510e0c00ed67ac896c21b847acadd8df29cf63a77470989d2

   ./yubihsm-shell --connector=yhusb:// --authkey=1 --password=password \
   --action=put-opaque \
   --object-id=7 --domains=1 \
   --algorithm=opaque-data --capabilities=none \
   --informat=hex --in=13086d684f4b1a1632178a8c5be08a2fb01287c4a78313c41373701eb8e66232

   ./yubihsm-shell --connector=yhusb:// --authkey=1 --password=password \
   --action=put-opaque \
   --object-id=8 --domains=1 \
   --algorithm=opaque-data --capabilities=none \
   --informat=hex --in=25296867ee96fa5b275af1b72f699efcb61586565d4c3c7e41f4b3e692471abd

   ./yubihsm-shell --connector=yhusb:// --authkey=1 --password=password \
   --action=put-opaque \
   --object-id=9 --domains=1 \
   --algorithm=opaque-data --capabilities=none \
   --informat=hex --in=10e1a313e573d96abe701d8848742cf88166dd2ded38ac22267a05d1d62baf71

   ./yubihsm-shell --connector=yhusb:// --authkey=1 --password=password \
   --action=put-opaque \
   --object-id=10 --domains=1 \
   --algorithm=opaque-data --capabilities=none \
   --informat=hex --in=0bdeebbad8f9b240192635c42f40f2d02ee524c5a3fe8cda53fb4897b08c66fe

   ./yubihsm-shell --connector=yhusb:// --authkey=1 --password=password \
   --action=put-opaque \
   --object-id=11 --domains=1 \
   --algorithm=opaque-data --capabilities=none \
   --informat=hex --in=5e8d5667ce78982a07242739ab03dc63c91e830c80a5b6adca777e3f216a405d
`

**Comment by usmansaleem** [comment]
Notes:
Sample meta file
The additional init config can be obtained from https://developers.yubico.com/YubiHSM2/Component_Reference/PKCS_11/. They have to be specified as a space separated string.

~~~
type: yubihsm
pkcs11ModulePath: /path/to/yubihsm_pkcs11.so
connectorUrl: yhusb://
additionalInitConfig: debug libdebug timeout=5
authId: 1
password: test
opaqueDataId: 1
keyType: BLS
~~~

**Comment by bgravenorst** [comment]
Done. See https://docs.web3signer.consensys.net/en/latest/HowTo/Store-Keys-HSM/Use-YubiHSM2/
