### ISSUE TITLE
Low watermark should not be changed by import

### ISSUE THREAD

**Issue by jframe** [ConsenSys/web3signer#290]
Low watermark should be not be changed by import. This should be a user initiated process to change the low watermark mostly like via a subcommand.

**Comment by rain-on** [comment]
This really depends on WHERE the imported blocks/attestations go WRT existing entries.

I.e. if ANY entry in the import is above our highest entry - the low water mark should be incremented.

This implies we must have an explicit low watermark per validator for both block_slot, attestation_source_epoch and attestation_target_epoch
