### ISSUE TITLE
Bad request replied upon request of a voluntary exit message

### ISSUE THREAD

**Issue by Magicking** [ConsenSys/web3signer#354]
On a web3signer functioning correctly (i.e signing correctly in combination with Teku on a testnet beacon chain) with web3signer version: web3signer/v20.11.0+9-g6e71e7b/linux-x86_64/-na-openjdk64bitservervm-java-11 (docker), when a Voluntary Exit Message (VEM) is requested, web3signer respond with a « Bad Request ».

Log on web3signer:
```signer_1         | 2020-12-28 12:12:50.621+00:00 | vert.x-eventloop-thread-2 | ERROR | LogErrorHandler | Failed request: http://signer:9000/api/v1/eth2/sign/0x8400ead5497554f557a7efd17e3515ac817369a6ef388352057ef2fdcb9b75d0a23731eccfd510bfd8d85fd73300d105```

According to https://consensys.github.io/web3signer/web3signer-eth2.html#operation/ETH2_SIGN the payload shown below is correct (i.e: all *required* fields are populated)

```
POST /api/v1/eth2/sign/0xa5bb1e8378db17c9a0bbe27a6ddf5be4bfcbc6514ef4d5bf94b739791093f7a1dfc86400b414c014f9a8e94697d138b2 HTTP/1.1
Host: signer:9000
User-Agent: Go-http-client/1.1
Content-Length: 176
Accept: */*
Accept-Encoding: application/json
Content-Type: application/json

{"fork_info":{"fork":{"current_version":"0x00000001","epoch":"0","previous_version":"0x00000001"}},"type":"VOLUNTARY_EXIT","voluntary_exit":{"epoch":"0","validator_index":"1"}}

HTTP/1.1 400 Bad Request
content-length: 11

Bad Request
```

**Comment by usmansaleem** [comment]
@Magicking `fork_info.genesis_validators_root` seems to be missing in your supplied payload. The current OpenApi spec at https://consensys.github.io/web3signer/web3signer-eth2.html#operation/ETH2_SIGN does show it so it is possible that an earlier version that you has used might be missing it.

~~~
{
  "type": "VOLUNTARY_EXIT",
  "fork_info": {
    "fork": {
      "previous_version": "string",
      "current_version": "string",
      "epoch": "string"
    },
    "genesis_validators_root": "string"
  },
  "signingRoot": "string",
  "voluntary_exit": {
    "epoch": "string",
    "validator_index": "string"
  }
}
~~~

**Comment by Magicking** [comment]
Not sure to follow, what might be the issue as the Genesis Validators Root is specified as optional in the spec you link and GVR is sent by Teku according to this discussion -> https://consensys.slack.com/archives/GU2QYGEF4/p1607478266205100?thread_ts=1607468953.204600&cid=GU2QYGEF4
