### ISSUE TITLE
Reloading keys

### ISSUE THREAD

**Issue by 3eph1r0th** [ConsenSys/web3signer#377]
It will be awesome if web3signer doesn't reload key if it is already in memory. Or even better to have 2 reload options: one like now, second without reloading the keys that are in memory.

**Comment by usmansaleem** [comment]
This has been implemented as part of commit https://github.com/ConsenSys/web3signer/commit/3d0a5d0153dae125dd48fcdd4f46261a5b619771

Closing the issue.
