### ISSUE TITLE
Support Altair 

### ISSUE THREAD

**Issue by ajsutton** [ConsenSys/web3signer#391]
There are a few changes in the upcoming Altair network upgrade which Web3Signer will need to support.

1. `BeaconBlockBody` has a new `sync_aggregate` field: https://github.com/ethereum/eth2.0-specs/blob/dev/specs/altair/beacon-chain.md#beaconblockbody
2. Sync Committees require signing a number of additional data structures.  There is no slashing protection required for these.
    a. `SyncCommitteeSignature` - signs a Bytes32 `beacon_block_root` https://github.com/ethereum/eth2.0-specs/blob/dev/specs/altair/validator.md#prepare-sync-committee-signature
    b. SyncCommittee selection_proof - signs a `SyncCommitteeSigningData` consisting of two UInt64 values (slot and subcommittee index): https://github.com/ethereum/eth2.0-specs/blob/dev/specs/altair/validator.md#aggregation-selection
    c. `ContributionAndProof` needs to be signed to create a `SignedContributionAndProof`: https://github.com/ethereum/eth2.0-specs/blob/dev/specs/altair/validator.md#broadcast-sync-committee-contribution

Teku will get support for signing these locally as part of https://github.com/ConsenSys/teku/pull/3838 with a base implementation added for `ExternalSigner` but the details of what to send Web3Signer will need to be sorted out and likely expanded on.

**Comment by arash009** [comment]
Is there a date for the network upgrade that this needs to be done by? Or the testnet date?

**Comment by ajsutton** [comment]
No exact dates but clients are working on it now - current guess in June/July for the upgrade to go live but likely want testnets running at least a month before that.
