### ISSUE TITLE
Eth2 --network cli option and Teku libraries upgrade

### ISSUE THREAD

**Issue by usmansaleem** [ConsenSys/web3signer#398]
- Introduce `--network` cli option (same as [Teku](https://docs.teku.consensys.net/en/latest/Reference/CLI/CLI-Syntax/#network))
-  Update Teku libraries version in Web3Signer.
- The web3signer `--network` option should match Teku's `--network` cli option at run time.

**Comment by bgravenorst** [comment]
Implemented here: https://github.com/ConsenSys/doc.web3signer/pull/90
