### ISSUE TITLE
Fix docker scan vulnerabilities

### ISSUE THREAD

**Issue by jmcruz1983** [ConsenSys/web3signer#407]
Checking the [Dockerfile](https://github.com/ConsenSys/web3signer/blob/master/docker/Dockerfile) seems that base image `openjdk:11-jre-slim-buster` is bringing some vulnerabilities flagged by some image scanning tools like [snyk](snyk.io) or [harbor](https://goharbor.io).

To get list of vulnerabilities you can run following command:
```
docker scan -f docker/Dockerfile pegasyseng/web3signer:develop --severity high
 ```

Producing following output:
```
Tested 91 dependencies for known issues, found 13 issues.

Base Image                  Vulnerabilities  Severity
openjdk:11-jre-slim-buster  63               13 high, 5 medium, 45 low
```

In addition some alternative base images are recommended:
```
Recommendations for base image upgrade:

Alternative image types
Base Image               Vulnerabilities  Severity
openjdk:16-ea-13-oracle  0                0 high, 0 medium, 0 low
openjdk:16-ea-16-jdk     0                0 high, 0 medium, 0 low
openjdk:16-ea-24-jdk     0                0 high, 0 medium, 0 low
openjdk:16-ea-33-oracle  0                0 high, 0 medium, 0 low
```

It is not critical but some private docker registry won't allow to pull such images with high severity vulnerabilities.

**Comment by usmansaleem** [comment]
Will be fixed by #408
