### ISSUE TITLE
ETH2: Eth1 withdrawal keys support

### ISSUE THREAD

**Issue by screwyprof** [ConsenSys/web3signer#413]
ETH2 chain now supports eth1 withdrawal keys. Does `web3signer` support this feature?

Will it work if the `eth1` key is formatted according to the spec and sent to `web3signer`?

```
withdrawal_credentials = ETH1_ADDRESS_WITHDRAWAL_PREFIX + b'\x00' * 11 + decode_hex(eth1_withdrawal_address)
// "0x01 + 0000000000000000000000 + 00000000219ab540356cbb839cbe05303d7705fa"
```

References:
1. https://github.com/ethereum/eth2.0-specs/pull/2149
2. https://ethresear.ch/t/simple-eth1-withdrawals-beacon-chain-centric/8256
3. https://github.com/ethereum/eth2.0-deposit-cli/blob/master/eth2deposit/credentials.py#L103

**Comment by usmansaleem** [comment]
Web3Signer deposit signing API doesn't perform any validation on the `withdrawal_credentials` and maps it to Bytes32. The caller would need to format `withdrawal_credentials` as per the new spec.
