### ISSUE TITLE
Add support for Prater Altair fork

### ISSUE THREAD

**Issue by paulhauner** [ConsenSys/web3signer#423]
The latest version of web3signer (21.8.0) does not recognize the Altair fork schedule for the Prater testnet.

Trying to sign any Altair objects (sync committee proofs, etc) on Prater will result in the following error from web3signer:

```
Fork at slot 1173120 does not support sync committees
```

According to the latest [Prater specifications](https://github.com/eth2-clients/eth2-networks/blob/7fa1b868985ee24aad65567f9250cf7fa86f97b1/shared/prater/config.yaml#L26), the fork happens at epoch 36660 (slot 1173120).

I understand that Altair support presently a WIP, but I thought it might be helpful if I pointed this out :)

**Comment by usmansaleem** [comment]
This should be taken care by upcoming PR https://github.com/ConsenSys/web3signer/pull/422

**Comment by usmansaleem** [comment]
@paulhauner This issue is addressed in following release. https://github.com/ConsenSys/web3signer/releases/tag/21.8.1-rc1
