### ISSUE TITLE
Only require block_body_root instead of full block body

### ISSUE THREAD

**Issue by ajsutton** [ConsenSys/web3signer#437]
Currently the Web3Signer API requires sending the entire beacon block body when signing blocks which is a lot of data and will get significantly bigger after the merge.  The contents of the block body do not affect whether signing is slashable so could be safely replaced by the block body root.

To preserve backwards compatibility I'd suggest updating Web3Signer to accept block_body_root as a field and only if it's not provided to then look for block_body.  Only one of them is required.

**Tasks**
* Update Teku to only send the block_body_root in the block signing request
* Update schema to add support block body root field
* Compute signing root for Beacon block using block body root

**Acceptance Criteria**
* Block body can still be used for the forks prior to the Bellatrix fork
* Block body root can be used instead of the full block body

**Comment by usmansaleem** [comment]
Fixed by #547
