### ISSUE TITLE
Helper library for signing transactions

### ISSUE THREAD

**Issue by rhlsthrm** [ConsenSys/web3signer#438]
I would like to use this library for signing Eth 1 transactions. Is there a helper library anywhere (i.e. a way to implement this in Ethers)?

**Comment by jframe** [comment]
We don't have any helper libraries unfortunately for using the web3signer API to sign Eth 1 transactions.

**Comment by rhlsthrm** [comment]
We are working on a helper class that implements the Ethers.js Signer interface. We can share it back here when it is ready. cc @sanchaymittal.
