### ISSUE TITLE
Single Config File for Keys in Vault

### ISSUE THREAD

**Issue by ciaranmcveigh-0xa** [ConsenSys/web3signer#440]
Currently when using W3S with vault you specify a key location folder via

`--key-store-path=/opt/web3signer/keys`

At this location you have your vault config files that specifies the keyPath, keyName, token etc.

```
type: "hashicorp"
keyType: "SECP256K1"
tlsEnabled: "true"
keyPath: "/v1/secret/data/secretPath"
keyName: "secretName"
serverHost: "localhost"
serverPort: "32895"
timeout: "10000"
token: "s.xxxxxxxxxxxxxxxxx”
```

The curent W3S requires you to have multiple files if you have multiple keys

If you have one location in vault ie /v1/secret/data/ where all keys are stored, each individual key wold be under  /v1/secret/data/$publickey and each individual key would have  the key name privateKey in their json ie

`{ "privateKey": "$privatekey" }`

It would be useful to have one config file that points to the vault base path "/v1/secret/data" and defines the common key name "privateKey", then W3S just scrapes all the secrets in the base path with the key name privatekey in their json

This save us having to add a new config file every time we add a new validator, we could just add the key to vault at the base path and it would be automatically picked up

I'm aware there is a reload api endpoint for W3S which reloads validators keys, this would need to be called after adding a new key to vault, from a discussion on discord

"reload API call which can load new config files, however, it may not load old config file as W3S caches file names"

I'm not sure if cached file names aren't reloaded but they would need to be with this feature

Tagging @jframe whom has some context from a conversation on discord

**Comment by iamhsk** [comment]
We are considering implementing bulk loading of hashicorp keys in the future. Please refer to #502. Closing this issue.
