### ISSUE TITLE
Not getting the same signature as ethers.signMessage()

### ISSUE THREAD

**Issue by sanchaymittal** [ConsenSys/web3signer#442]
Web3Signer signing doesn't return the same signature as ethers wallet.signMessage().
Is the signing method for web3Signer different from the ethers standard?

To reproduce:
```ts describe.only("Web3Signer", () => {
  it("should run", async () => {
    const data = "hello";
    const message = ethers.utils.hashMessage(data);

    const publicKeys: AxiosResponse<string> = await axios.get(`${web3HostedUrl}/api/v1/eth1/publicKeys`);
    const identifier = publicKeys.data[0]

     const response: AxiosResponse<string> = await axios.post(`${web3HostedUrl}/api/v1/eth1/sign/${identifier}`, {
         data: message,
      });

    const wallet = Wallet.fromMnemonic("<mnemonic goes here>");
    const cRes = await wallet.signMessage(message);

    expect(response.data).to.be.eq(cRes);
  });
});

**Comment by usmansaleem** [comment]
@sanchaymittal Can you try to send bytes in hex format for `data` to web3signer instead of its hash? 
i.e. something like 
~~~
const data = Buffer.from('hello', 'utf8').toString('hex');
...
 const response: AxiosResponse<string> = await axios.post(`${web3HostedUrl}/api/v1/eth1/sign/${identifier}`, {
         data: data,
      });

~~~

**Comment by jframe** [comment]
The wallet.signMessage in ethers is doing an EIP-191 compliant signing looking at this https://docs.ethers.io/v5/api/signer/#Signer-signMessage

In Web3Signer we are not doing a EIP-191 compliant signing. So you will need to append "\x19Ethereum Signed Message:\n" and the length of the message before sending to your data string before sending it to web3signer.
