### ISSUE TITLE
Discord invite link

### ISSUE THREAD

**Issue by awrelll** [ConsenSys/web3signer#453]
Hi,
I was looking to get some support and found out the Discord link expired. 
Is there a way to fix this ?
Thanks

**Comment by jframe** [comment]
Thanks for letting us know. I just confirmed and the discord link in the [documentation page](https://docs.web3signer.consensys.net/en/latest/) is out of date. Will get that updated.

This is current discord link for web3signer https://discord.gg/KMh2Mjh which is in the readme but was out of date in the docs.
