### ISSUE TITLE
Is Azure Key vault supported as part of Web3Signer with ETH1 ?

### ISSUE THREAD

**Issue by Sugam31** [ConsenSys/web3signer#476]
I was trying to run the web3signer with Azure parameters using ETH1.This is the command I was trying to execute to run the web3signer:-

web3signer eth1 --azure-vault-enabled=true --azure-client-id=xxxx --azure-client-secret=xxxxx azure-tenant-id=xxxxx --azure-vault-name=xxxxx.

However, it failed with the following error:-
Error parsing parameters: Unknown options: --azure-vault-enabled=true --azure-client-id=xxxx --azure-client-secret=xxxx  --azure-tenant-id=xxxx  --azure-vault-name=xxxx

**Comment by jframe** [comment]
The Azure bulk key loading is only supported for Eth2 signing at the moment see the documentation details here https://docs.web3signer.consensys.net/en/latest/HowTo/Use-Signing-Keys/#bulk-loading-ethereum-20-keys.
