### ISSUE TITLE
If there is a plan of adding signTransaction method using web3signer?

### ISSUE THREAD

**Issue by Sugam31** [ConsenSys/web3signer#477]
Hi team, 

As per the documentation of web3signer,there is only an API available to sign data but sign transaction method is not available. Is there any plan of adding signTransaction method?

**Comment by jframe** [comment]
There are currently no plans to add the Ethereum signTransaction RPC method to Web3Signer. If you require this functionality you can use Quorum key manager https://docs.quorum-key-manager.consensys.net/en/latest/.
