### ISSUE TITLE
Inconsistent API url:s

### ISSUE THREAD

**Issue by arnetheduck** [ConsenSys/web3signer#478]
https://consensys.github.io/web3signer/web3signer-eth2.html?version=21.10.4

While implementing this in Nimbus, we found a few oddities around naming - are the API url:s in the openapi yaml correct?

* `/api/v1/eth2/sign/{identifier}`, `/api/v1/eth2/publicKeys` contain `/api` while `/eth/v1/keystores` is in `eth` and some requests are "top-level"
* in https://ethereum.github.io/beacon-APIs where the `/eth` namespace comes from, paths have an additional level of nesting that create "sub-namespaces" - `/eth/v1/beacon/XXX` - the overlap in this spec along with the slightly different structure might prove troublesome in the future

**Comment by jframe** [comment]
Hi @arnetheduck, The APIs URLs are correct. 

- Unfortunately we added the `/api/v1/eth2` signing APIs early so it's an oversight that this doesn't align nicely with the standard beacon APIs using /eth namespace.
- The `/eth/v1/keystores` uses that namespace as we need align with the keymanager API https://github.com/ethereum/keymanager-APIs/
- We added the `/reload` and `/upcheck` at the top level as these are not specific Eth2 or Eth1 signing and are specific web3signer.

Hopefully in the future we can clean up the APIs a bit.
