### ISSUE TITLE
Setup Web3Signer on a merge testnet

### ISSUE THREAD

**Issue by jframe** [ConsenSys/web3signer#487]
Setup Web3Signer on a merge testnet.

Tasks:
1. Decide which testnet is best at the time - currently kiln, ropsten may be an option soon
2. Assuming [#463](https://github.com/ConsenSys/protocol-misc/issues/463) is done first, set up ansible configuration for this testnet
3. Since this will be the second testnet setup (after prater) consider if and how best to automate the approach

**Acceptance Criteria**
* Web3Signer is running a merge testnet

**Comment by usmansaleem** [comment]
See #571 .. can this ticket covers 10K keys setup
