### ISSUE TITLE
Subcommand to adjust the signing protection watermark

### ISSUE THREAD

**Issue by jframe** [ConsenSys/web3signer#493]
Add a subcommand that will allow adjusting of the slashing protection watermark. This would be useful if all the slashing protection data has been lost and allow web3signer to be safely used to sign again by setting the watermark to a future slot.

Tasks
* Create new subcommand at the same level as Eth2Export, Eth2Import, etc. (e.g. SlashingProtectionSubCommand or WatermarkSubCommand?)
* Create service layer (may be small enough to go in subcommand) which uses tech.pegasys.teku.spec.Spec to determine the epoch/slot as the default for the command.
* Allow user to configure their own epoch/slot?
* Consider adding an acceptance test

**Notes**
* An approach similar to the Teku signing-protection repair subcommand https://docs.teku.consensys.net/en/latest/Reference/CLI/Subcommands/Slashing-Protection/#repair could be used.
* If automatically setting the slot and epoch watermark we can use the Teku spec object and calculate the exact epoch and slot
* Optional nice to have to do in another story: take the opportunity to prune the DB.
* Probably only need to configure one of epoch or slot.
* Epoch source and target can be the same value.

**Acceptance Criteria**
* Subcommand that allows setting the attestation and block watermark to the provided values
* Can automatically set the slot and epoch to next epoch given the network name
* Should set watermark for all the validators the web3signer instance knows about (rather than everything in the database), c.f. how pruning works: https://github.com/ConsenSys/web3signer/blob/6fa9df2fa42a8a67da19eb6fe5f210c4b9467d76/slashing-protection/src/main/java/tech/pegasys/web3signer/slashingprotection/DbSlashingProtection.java#L264

Tasks
- [ ] Create watermark subcommand
- [ ] Update watermarks for all known validators

**Comment by joaorodrigues-consensys** [comment]
> Subcommand that allows setting the attestation and block watermark to the provided values

Besides attestations & block proposals, you might need to cover other cases like sync committees (altair) and signed blinded blocks (bellatrix).

**Comment by jframe** [comment]
Sync committee signings aren't stored as there are is no slashing that can be done on these.
The signed blinded blocks are treated the same as blocks since we pass in the body root now instead of the entire body. So these will be pruned as part of the block pruning.
