### ISSUE TITLE
AWS key retrieval without passwords/token in config

### ISSUE THREAD

**Issue by jframe** [ConsenSys/web3signer#500]
AWS key retrieval without passwords/token in config

**Tasks**
* This may actually work so this story is focused on testing the functionality to make sure it is there and works as expected

**Acceptance Criteria**
* Explicit config to enable managed identity mode, so it can't be accidentally used
* Once enabled should respect the AWS ACL. Should only be able to access keys you are assigned
* Keys can be retrieved without secrets
* Acceptance tests for each identity mode

**Comment by georgep9** [comment]
[Uploading... web3signer-aws-environment-test.txt]

**Comment by georgep9** [comment]
![image.png](https://images.zenhubusercontent.com/61aff2f459e1b232cb50ddc9/b60796b6-868e-4543-add6-fdaceb8542fa)
