### ISSUE TITLE
allow `network` command line argument to accept a yaml config file

### ISSUE THREAD

**Issue by rolfyone** [ConsenSys/web3signer#522]
Teku allows a yaml network config to be passed which can be great for testing or just setting up custom network configurations.

I'm hoping web3signer can do the same, and then i can pass the same network configuration file into all of the nodes in an acceptance test file, as it appears to pickup different configurations in circleci in teku to what it does running locally.

I think this would also be good for users if they're not using mainnet, and also potentially for testing web3signer if configuration needs to be tweaked to see issues.

**Comment by usmansaleem** [comment]
@rolfyone Web3Signer uses Teku libraries to parse network configuration.

**Comment by usmansaleem** [comment]
There is also an open PR waiting on Teku release that fixes overriding of config options in custom network file. https://github.com/ConsenSys/web3signer/pull/515

**Comment by rolfyone** [comment]
teku allows specifying a file as that option, but when I do it fails saying that it's an invalid value, so I'm not sure if theres some small but important difference somewhere...

**Comment by rolfyone** [comment]
Ok it does look like my version of web3signer was slightly out of date, and this functionality is working - thanks for your help Uzi!
