### ISSUE TITLE
Error while installing slashing protection database v10

### ISSUE THREAD

**Issue by mgarciate** [ConsenSys/web3signer#525]
There's an error while installing the web3signer with the slashing protection database. After moving all sql files from 
`/slashing-protection/src/main/resources/migrations/postgresql/*.sql`
to
`/docker-entrypoint-initdb.d/`

Scripts will run alphabetically, so V10__validator_enabled_status.sql will be executed before V1__initial.sql and never after V9__upsert_validators.sql

**Comment by usmansaleem** [comment]
Hi @mgarciate, thank you for the PR, the changes were safe specially when dealing with Flyway so I have merged it. However, during my testing I observed that `/docker-entrypoint-initdb.d/` would only work when pg is initialization itself for the very first time. If new schema version sql files are introduced by Web3Signer in future, you would need to manually run them. An alternate (and recommended) approach is to use flyway to automatically manage these version files. See this [docker-compose](https://github.com/usmansaleem/signers_docker_compose/blob/main/web3signer-pg-docker-compose/pg/docker-compose-pg.yml) file as an example which extracts schema file from web3signer docker container in a shared volume which is then executed by flyway container.

**Comment by mgarciate** [comment]
> Hi @mgarciate, thank you for the PR, the changes were safe specially when dealing with Flyway so I have merged it. However, during my testing I observed that `/docker-entrypoint-initdb.d/` would only work when pg is initialization itself for the very first time. If new schema version sql files are introduced by Web3Signer in future, you would need to manually run them. An alternate (and recommended) approach is to use flyway to automatically manage these version files. See this [docker-compose](https://github.com/usmansaleem/signers_docker_compose/blob/main/web3signer-pg-docker-compose/pg/docker-compose-pg.yml) file as an example which extracts schema file from web3signer docker container in a shared volume which is then executed by flyway container.

Thank you @usmansaleem we'll take a look. cc @pablomendezroyo
