### ISSUE TITLE
Slashing protection interchange import to allow duplicate blocks and attestations

### ISSUE THREAD

**Issue by jframe** [ConsenSys/web3signer#583]
Slashing protection import should allow importing of duplication blocks and attestations as this represents what has happened. This is also affecting the slashing protection interchange test "multiple_interchanges_single_validator_multiple_blocks_out_of_order" which is currently being ignored.

This is occurring because web3signer has a postgresql unique constraints on both the signed blocks and signed attestations to prevent duplication blocks and attestations being inserted into the database, a very good thing otherwise we could get slashed.

One solution could be to relax the constraint so it only applies to signings not to import of existing data. This can be done by changing the unique constrain to a unique partial index.

i.e. for blocks this could work
```
ALTER TABLE signed_blocks
DROP CONSTRAINT unique_signed_block;

ALTER TABLE signed_blocks
ADD COLUMN imported boolean NOT NULL default false;

CREATE UNIQUE INDEX unique_signed_block ON signed_blocks (validator_id, slot)
WHERE imported is false;
```

**Comment by usmansaleem** [comment]
Closing due to no action.
