### ISSUE TITLE
Rename key-store-path command line option

### ISSUE THREAD

**Issue by jframe** [Consensys/web3signer#586]
Rename the command line option --key-store-path as it is confusing since it implies that it is related to key stores. This is the key config directory and is for more than just keystore files. It is also similar in name the recently added keystore bulk loading command line options https://docs.web3signer.consensys.net/en/latest/Reference/CLI/CLI-Subcommands/#keystores-path.

Tasks
- [x] Keep old name as an alias and deprecate
- [x] New name

Note to dev: Make sure to specify the new cli option as the first option so that any error reporting by PicoCli mentions new option, for example:
```
  @Option(
      names = {"--key-config-path", "--key-store-path"},
      description = "The path to a directory storing yaml files defining available keys",
```

The AT should test `key-config-path` and `key-store-path` i.e. both the new and deprecated value and make sure that the config file AT picks them up.

**Comment by jframe** [comment]
@james-prysm No decision has been made on what the name would change to. Was thinking --key-config-path would work well but that's not locked in yet. Will update this ticket once we decide on the new command line option name.

**Comment by siladu** [comment]
@james-prysm we went with --key-config-path but --key-store-path still works

**Comment by james-prysm** [comment]
awesome thanks for letting me know
