### ISSUE TITLE
Remove helm chart

### ISSUE THREAD

**Issue by siladu** [ConsenSys/web3signer#590]
https://github.com/ConsenSys/web3signer/tree/master/helm/web3signer

**Comment by Filter94** [comment]
Why was it removed?

**Comment by siladu** [comment]
> Why was it removed?

https://github.com/Consensys/web3signer/releases/tag/23.6.0

> Removed unmaintained and out-of-date helm chart https://github.com/ConsenSys/web3signer/pull/802
