### ISSUE TITLE
Google Secret Manager Support

### ISSUE THREAD

**Issue by shayanb** [Consensys/web3signer#676]
Looking at the documentations on how to [use](https://docs.web3signer.consensys.net/en/latest/HowTo/Use-Signing-Keys/) Web3Signer and [key storage](https://docs.web3signer.consensys.net/en/latest/Reference/Key-Configuration-Files/), I noticed that most secret manamgers are documented but didn't find anything about [Google Secret Manager](https://cloud.google.com/secret-manager). Wondering if this is just lack of documentation or an issue with supporting the GSM API?

**Comment by shayanb** [comment]
Almost answering my question, it seems that the interface is not implemented and needs to be added here to support GSM:
- https://github.com/ConsenSys/web3signer/tree/master/signing/src/main/java/tech/pegasys/web3signer/signing/config

Some resources on GSM Java implementation:
- https://github.com/googleapis/java-secretmanager
- https://cloud.google.com/secret-manager/docs/creating-and-accessing-secrets#secretmanager-create-secret-java

**Comment by siladu** [comment]
Hi @shayanb, we don't have a Google Secret Manager implementation, however it would be a good thing to add so thanks for bringing his up.
We will add this to our backlog, but can't currently provide a timeline for when we'll get to it.

Contributions most welcome :)

**Comment by theSamPadilla** [comment]
Hey folks!

Google Cloud Web3 team here. Wanted to follow up on this and see if there were any updates.

Happy to provide some support if needed.

**Comment by siladu** [comment]
Hi @theSamPadilla - thanks for the offer of support!

We definitely intend to add this to web3signer, but we still don't have the time to prioritise this right now unfortunately. 

Would be interested in hearing more about if and how Google intend to use it. That could potentially affect the priority of this issue.
Might be good to start a discussion on the #web3signer on our Discord: https://discord.gg/consensys
