### ISSUE TITLE
Investigate changes needed for Capella in Web3Signer

### ISSUE THREAD

**Issue by jframe** [ConsenSys/web3signer#682]
For Capella CL updates, there’s new block bodies and blinded block bodies to cater for sending bls_to_execution changes and withdrawals. 

- Identify changes for Web3Signer in terms of withdrawl signing requests (New API or modifications to existing API?). 
- Coordinate with EL team (such as Teku) to finalize the changes
- Create new issues if required.

**Timebox to 0.5 day**

**Comment by james-prysm** [comment]
might be a duplicate or related to https://github.com/ConsenSys/web3signer/issues/673
