### ISSUE TITLE
Investigate changes needed for EIP-4844 in Web3Signer

### ISSUE THREAD

**Issue by jframe** [Consensys/web3signer#683]
- Identify changes for Web3Signer in terms of EIP-4844 changes (New API or modifications to existing API?).
- Coordinate with EL team (such as Teku) to finalize the changes
- Create new issues if required.

(Time box: 1-2 days)

**Comment by siladu** [comment]
- Implement signBlobSidecar and signBlindedBlobSidecar: https://github.com/Consensys/teku/blob/master/validator/client/src/main/java/tech/pegasys/teku/validator/client/signer/ExternalSigner.java#L131-L144
- Add to `ExternalSignerIntegrationTest` and/or new test `ExternalSignerDenebBlockSigningIntegrationTest`?
- Web3signer API Spec Changes and any required config changes, similar to https://github.com/Consensys/web3signer/commit/7edd73b8ad07099fea78d6b063338fdefdb72516
