### ISSUE TITLE
Wrong import of keystores using remote keymanager API returns HTTP code 200

### ISSUE THREAD

**Issue by pablomendezroyo** [ConsenSys/web3signer#713]
**Issue**
Importing keystores using the remote keymanager API with a wrong password result in the following response
```
[{"status":"error","message":"Error importing keystore: Unable to add validator"}]
```
With the following HTTP status code
```
200
```
**Expected behavior**
The response status code should be a 4.x.x. Probably a bad request 400

**Comment by pablomendezroyo** [comment]
I guess this is implemented this way to handle multiple imports

**Comment by pablomendezroyo** [comment]
In any case the error is not verbose enough, I get an array of error/succeed imports. How can I know which belongs to which pubkey?

**Comment by jframe** [comment]
Hi @pablomendezroyo, We are returning a 200 status code as this how is defined in the key manager spec https://github.com/ethereum/keymanager-APIs/blob/master/apis/local_keystores.yaml#L96. The API flow makes this a bit clearer https://github.com/ethereum/keymanager-APIs/tree/master/flows#process-flows.

Agree that the error could be clearer, think can do something improve that.

The success/error responses match the same order in the array passed into the import post request.
