### ISSUE TITLE
Web3Signer Deneb Support

### ISSUE THREAD

**Issue by siladu** [Consensys/web3signer#726]
**Tasks**

- [x] Anything that comes out of https://github.com/ConsenSys/web3signer/issues/683
- [x] Open API spec changes

**Comment by StefanBratanov** [comment]
@siladu This should also make it in Deneb and would require changes in Web3Signer I think: https://eips.ethereum.org/EIPS/eip-7044

This is our local signing PR for this change: https://github.com/Consensys/teku/pull/7394

**Comment by siladu** [comment]
> @siladu This should also make it in Deneb and would require changes in Web3Signer I think: https://eips.ethereum.org/EIPS/eip-7044
> 
> This is our local signing PR for this change: [Consensys/teku#7394](https://github.com/Consensys/teku/pull/7394)

Thanks for the heads-up @StefanBratanov - looks like we might get it for free when we pull in the correct teku library version 🤞 
Will investigate anyway

**Comment by eddort** [comment]
Hello! Could you please confirm if Web3signer already supports EIP-7044? There will be a new fork on February 7th at Holesky, and it would be great to have everything checked in time.

**Comment by jframe** [comment]
@eddort Web3Signer already supports EIP-7044. We reused the voluntary exit signing from Teku to provide this.

**Comment by siladu** [comment]
I think we can close this issue. @jframe please reopen if not.
