### ISSUE TITLE
Build manifest docker step fails intermittently

### ISSUE THREAD

**Issue by jframe** [ConsenSys/web3signer#733]
The circle build fails intermittently on the manifestDocker step. It passes after a rerun of the job.

This is a recent example of it failing https://app.circleci.com/pipelines/github/ConsenSys/web3signer/2570/workflows/8df031ae-8dc3-45bd-b77d-28a2bbac2512/jobs/8670

**Comment by usmansaleem** [comment]
Reopen if it surfaces again.
