### ISSUE TITLE
Large number of Hashicorp configuration files causes "BindException: Cannot assign requested address"

### ISSUE THREAD

**Issue by gg718** [ConsenSys/web3signer#736]
Using the latest version of Web3Signer ([v23.3.0](https://github.com/ConsenSys/web3signer/releases/tag/23.3.0)).

---

While running a test with ~30k keys (each defined in a separate file, so ~30k files), I noticed that when I reached somewhere around the 28230th to 28250th key, I consistently experienced the following error:

> `2023-03-13 18:06:47.068+00:00 | ForkJoinPool-1-worker-12 | ERROR | SignerLoader | Error parsing signing metadata file /tmp/key-28231.yaml: BindException: Cannot assign requested address`

The logs also went on to say:

> `2023-03-13 18:06:52.054+00:00 | ForkJoinPool-2-worker-1 | INFO  | SignerLoader | Total configuration metadata files processed: 30984`
>
> `2023-03-13 18:06:52.054+00:00 | ForkJoinPool-2-worker-1 | INFO  | SignerLoader | Total signers loaded from configuration files: 28230 in 00:00:32.122`

No number of restarts of Web3Signer, nor increasing CPU/memory resources, resolved the issue.

---

**Update:** Seems related to `/proc/sys/net/ipv4/ip_local_port_range` ([ref](https://stackoverflow.com/q/31876441)) – I have exactly 28231 ports available and these are exhausted while processing the keys; presumably since I am fetching the keys from HashiCorp Vault. Is there some workaround for this?

**Comment by usmansaleem** [comment]
Hi @gg718, we might need to introduce http client sharing for vault (specially if all the keys are loaded from same vault server using same credentials. Can you specify your use case a bit more i.e. are all secrets loaded from same secret engine and from same path?

**Comment by usmansaleem** [comment]
You may try to temporary increase the local port range if you have sudo access. https://www.cyberciti.biz/tips/linux-increase-outgoing-network-sockets-range.html

**Comment by gg718** [comment]
@usmansaleem That's pretty much exactly my use case, as you described. Same secret engine, keys stored under similar paths (e.g. `secret/goerli/{1,2,3,etc}`), with the private key being stored under each of those paths. Same Vault server, same credentials.

**Comment by usmansaleem** [comment]
@gg718 The fix to handling large number of configuration files dealing with Hashicorp has been merged to master branch. You should be able to try it out using `develop` tag of web3signer's docker image.
