### ISSUE TITLE
Could web3signer support zhejiang testnet?

### ISSUE THREAD

**Issue by haohaodie** [ConsenSys/web3signer#749]

**Comment by jframe** [comment]
You can provide a custom yaml configuration file https://github.com/ethpandaops/withdrawals-testnet/blob/master/zhejiang-testnet/custom_config_data/config.yaml to network option https://docs.web3signer.consensys.net/Reference/CLI/CLI-Subcommands#network to use the Zhejiang testnet.

**Comment by siladu** [comment]
Zhejiang was decommissioned.
