### ISSUE TITLE
Remove usage of signers library

### ISSUE THREAD

**Issue by jframe** [ConsenSys/web3signer#771]
Remove the usage of the signers library and inline the code as a module in web3signer. This removes additional overhead from the development and release process. 

Move the following modules
- [x] keystore to web3signer
- [x] signing to web3signer
- [x] acceptance-tests to web3signer
- [ ] bls-keystore to teku

**Comment by non-fungible-nelson** [comment]
Check with Teku team to see what usage of signers library will need to be supported elsewhere.
