### ISSUE TITLE
Stop Web3signer from importing EXITED validators

### ISSUE THREAD

**Issue by beetrootkid** [Consensys/web3signer#781]
Now that Shapella has come and gone, we are more likely to see keys in the EXITED state.  As per protocol, these keys can never be re-used. We are expecting to generate more keys into existing clusters, taking the total up from 10K to, for example, 20K. Half of these potentially could have been exited and importing those no-longer-in-use keys will take time on start-up.

Is there a way for web3signer to understand 'state' ? In our infrastructure, we are reluctant to either delete keys from the vault/secrets manager or, in fact, add further data into that secure space. Perhaps the signer can grab state from a flat-file or some other mechanism on start-up? There's no real need for this to be super dynamic because our impression is the main time cost will be on start-up.

We have the validator state and can make that available alongside the public key.

**Comment by beetrootkid** [comment]
One thing to note: Right now, this doesn't feel like a priority action/requirement but just want to put this on all our radars.

**Comment by non-fungible-nelson** [comment]
@beetrootkid Let's have our team's connect on this

**Comment by beetrootkid** [comment]
@non-fungible-nelson  - yes, let's talk before my exit. Shall I set up a meeting with the team? (It might be hard to include you because of your timezone)

**Comment by beetrootkid** [comment]
Hi @non-fungible-nelson  - after a conversation between the teams, we've decided to close this issue for now. The only point this really creates load is during start-up. There's a lot of complexity involved to address it and the benefits delivered don't warrant addressing it.

**Comment by non-fungible-nelson** [comment]
Thank you! Let's wait for validator indices reuse
