### ISSUE TITLE
Structure message signing EIP-712

### ISSUE THREAD

**Issue by gfukushima** [Consensys/web3signer#831]
Implement structured message signing RPC `eth_signTypedData`

"Aim of EIP-712 is to simplify off-chain message signing for efficient on-chain verification"

> The method eth_signTypedData is added to the Ethereum JSON-RPC. The method parallels eth_sign.

(NB: it's not actually in the spec https://github.com/ethereum/execution-apis/blob/main/src/eth/sign.yaml)

Tasks
- [x] Check that web3j implementation is up to date (uses eth_signTypedData_v4?)
- [x] Upgrade web3j to v4.9.7+
- [x] Create new eth_signTypedData endpoint
- [x]  Use StructuredDataEncoder https://github.com/web3j/web3j/blob/e80f040bc43805522451d8050b310fae0d3499f8/crypto/src/main/java/org/web3j/crypto/StructuredDataEncoder.java#L44 to encode the data needs to be signed. Don't use Sign.signTypedData directly as we need sign using keys from vaults https://github.com/web3j/web3j/blob/2ad9a8b4b9411de13c6d09e8392a51213d8160f0/crypto/src/main/java/org/web3j/crypto/Sign.java#L85
- [x]  Automated tests

Resources

 - https://eips.ethereum.org/EIPS/eip-712
-  https://ethereum-magicians.org/t/eip-712-eth-signtypeddata-as-a-standard-for-machine-verifiable-and-human-readable-typed-data-signing/397
- https://docs.web3j.io/4.10.0/use_cases/meta_transaction/#eip-712-typed-structured-data-json
 - https://docs.metamask.io/wallet/how-to/sign-data/#use-eth_signtypeddata_v4
 - https://medium.com/metamask/eip712-is-coming-what-to-expect-and-how-to-use-it-bb92fd1a7a26
 - https://metamask.github.io/test-dapp/#signTypedDataV4

**Comment by siladu** [comment]
> Check that web3j implementation is up to date (uses eth_signTypedData_v4?)

@gfukushima what was the outcome of this? Which version is web3j using?
