### ISSUE TITLE
Failed to read database version, expected 11

### ISSUE THREAD

**Issue by slickfive** [Consensys/web3signer#863]
When invoking the web3signer, I receive the following message 'Failed to initialize Web3Signer
Cause: Failed to read database version, expected 11'. 

I have downgraded to Postgress 11, but it still fails with the message. Any suggestions or help would be much appreciated. 

Current versions:

web3signer-23.6.0
postgresql-11
openjdk 11.0.19 2023-04-18

**Comment by slickfive** [comment]
I've now updated the postgres to the latest version, and see the following:

FATAL: database "web3signer" does not exist

How is the database created?

**Comment by siladu** [comment]
> Cause: Failed to read database version, expected 11'.

This actually refers to the web3signer database version, rather than postgres.

Please follow these instructions for running the database schema migration scripts: https://docs.web3signer.consensys.net/how-to/configure-slashing-protection#load-the-database-schema

**Comment by siladu** [comment]
@slickfive please see my previous comment and close this issue if everything works for you :)

**Comment by usmansaleem** [comment]
@slickfive Closing ticket, feel free to reopen if you are still facing issues.
