### ISSUE TITLE
[Question] Is it possible to connect multiple Web3Signers running different keys to the same database?

### ISSUE THREAD

**Issue by gg718** [Consensys/web3signer#866]
I am looking to "shard" Web3Signer to improve loading times and resource utilization, and one idea I had was to split keys across Web3Signer instances, but have them all connect to the same backend database.

**Example:** I have 5000 keys. I split these across 5 Web3Signer instances, each loading 1000 keys. They all connect to the same database.

Would a setup like this work?

**Comment by jframe** [comment]
@gg718 Yes that would work. Multiple Web3Signers can share the same database. Each instance will only update and interact with the data for it's own keys. And the pruning only affects the associated data for the keys that each instance has loaded.

**Comment by jframe** [comment]
How long it it taking to start web3signer and load all the keys? We print the key loading times in the startup log of web3signer. And how are you storing keys? I'm not sure if there is anything we can do improve this but it would be good to know if we have performance issue with loading keys in web3signer.

**Comment by gg718** [comment]
@jframe Thanks for the info!

I am currently performing a stress test for a client so I can understand Web3Signer's limits, and the setup I am running is:

* 70k keys
* Each key stored in a separate path in HashiCorp Vault

Loading times are reasonable at the moment but perhaps could be better, so wanted to consider alternatives (e.g. sharding) if possible:

```
Total signers loaded from configuration files: 70000 in 00:01:20.298 with error count 0
```

At this scale, are there any performance considerations or tweaks you might suggest (eg. some hidden `--X` flags or JVM parameters) that I might not have considered?
