### ISSUE TITLE
Key files are intermittently not reloaded when hitting `/reload` endpoint

### ISSUE THREAD

**Issue by gg718** [Consensys/web3signer#885]
This is a particularly tricky issue to debug because it's intermittent, and so far I have not managed to reliably reproduce it, but I can say with certainty it happens every week or so and requires manual intervention when I receive alerts that attestations are being missed.

I'll outline the rough setup which causes the issue and hopefully you'll be able to (help me) figure out what's going on, and confirm whether there is an underlying caching bug in the Web3Signer key reload logic or not.

---

Using Web3Signer v23.3.1:

* Write 30k individual key files to disk, each with a config similar to the following:

```yaml
keyName: key
keyPath: /v1/secret/data/goerli/12345
keyType: BLS
serverHost: localhost
serverPort: 8200
timeout: 30000
tlsEnabled: false
token: unused_handled_by_vault_proxy
type: hashicorp
```
* Hit Web3Signer's [`/reload`](https://consensys.github.io/web3signer/web3signer-eth2.html#tag/Reload-Signer-Keys) endpoint to load the first batch of keys

* Write another 30k individual key files to disk, each with a config similar to the above

* Hit Web3Signer's [`/reload`](https://consensys.github.io/web3signer/web3signer-eth2.html#tag/Reload-Signer-Keys) endpoint to load the next batch of keys

* Hit Web3Signer's [`/api/v1/eth2/publicKeys`](https://consensys.github.io/web3signer/web3signer-eth2.html#tag/Public-Key/operation/ETH2_LIST) endpoint and observe that less than 60k keys are actually loaded. In this example, 59957 keys are loaded and 43 are missing. This is the intermittent part and is hard to reliably reproduce.

* Hit Web3Signer's [`/reload`](https://consensys.github.io/web3signer/web3signer-eth2.html#tag/Reload-Signer-Keys) endpoint and note that it reports that there are no new keys to load, even though 43 are missing:

```
2023-08-22 09:32:39.146+00:00 | ForkJoinPool-117-worker-1 | INFO  | SignerLoader | Parsing configuration metadata files
2023-08-22 09:32:39.146+00:00 | ForkJoinPool-117-worker-1 | INFO  | SignerLoader | Total configuration metadata files processed: 0
2023-08-22 09:32:39.146+00:00 | ForkJoinPool-117-worker-1 | INFO  | SignerLoader | Total signers loaded from configuration files: 0 in 00:00:00.000 with error count 0
2023-08-22 09:32:39.146+00:00 | pool-2-thread-1 | WARN  | Eth2Runner | No BLS keys loaded. Check that the key store has BLS key config files
2023-08-22 09:32:39.146+00:00 | pool-2-thread-1 | INFO  | DefaultArtifactSignerProvider | Total signers (keys) currently loaded in memory: 59957
```

* Identify the files for the keys that are not returned by Web3Signer's API (i.e. not loaded)

* Manually `touch` the 43 keys that have not been correctly loaded to update the modification time

* Hit Web3Signer's [`/reload`](https://consensys.github.io/web3signer/web3signer-eth2.html#tag/Reload-Signer-Keys) endpoint again and note that it reports:

```
2023-08-22 09:45:27.281+00:00 | pool-2-thread-1 | INFO  | RegisteredValidators | Validators registered successfully in database:43
```

---

So it seems that somehow Web3Signer is picking up all the key files the first time around, failing to load a subset into memory, but incorrectly caching the fact the the keys have been loaded, and then failing to pick them up on the next `/reload`, until the modtime is manually changed.

I tried to follow the code through to see how this might be happening, but didn't get very far. But there definitely seems to be an issue related having a large number of keys, (re)loading, and caching.

**Comment by gg718** [comment]
Have also noticed that after touching the files as described above and successfully reloading them, the logs report that all 60k keys were loaded:

```
2023-08-22 10:49:05.476+00:00 | ForkJoinPool-121-worker-1 | INFO  | SignerLoader | Total configuration metadata files processed: 60000
2023-08-22 10:49:05.476+00:00 | ForkJoinPool-121-worker-1 | INFO  | SignerLoader | Total signers loaded from configuration files: 60000 in 00:01:41.635 with error count 0
```

However when I list the public keys via [`/api/v1/eth2/publicKeys`](https://consensys.github.io/web3signer/web3signer-eth2.html#tag/Public-Key/operation/ETH2_LIST), I get the following back:

```
$ curl -sS http://localhost:9000/api/v1/eth2/publicKeys | jq length
59986
```

So something fishy is definitely going on here.

**Comment by usmansaleem** [comment]
Hi @gg718 

Thank you for reporting this. I'll try to reproduce it locally. Meanwhile, can you enable serial processing of metadata config files and see if that makes any difference in regards to loading all the files (both at restart and /reload)? `--Xmetadata-files-parallel-processing-enabled=false`

**Comment by usmansaleem** [comment]
@gg718 you should definitely upgrade to 23.6.0 (or possibly to 23.8.1 once it is announced as it uses Java 17 both for compiling and runtime). It also contains for hashicorp using http 1.1. 23.6.0 contains other fixes related to database contention as well. I suspect that you are still facing the local socket running out issue when connecting to hashicorp. Using serial processing would eliminate this possibility. You can then attempt to increase the local socket connections.

**Comment by usmansaleem** [comment]
@gg718 any updates trying to observe this issue with latest web3signer release?

**Comment by gg718** [comment]
@usmansaleem Only managed to upgrade to v23.8.1 on Monday, so will monitor the situation and let you know. So far, I haven't noticed anything strange going on.

**Comment by usmansaleem** [comment]
Closing the issue. Feel free to reopen this issue or create a new one if regression is noticed.
