### ISSUE TITLE
Test block/blob signing in W3S + CL/EL combo or devnet

### ISSUE THREAD

**Issue by gfukushima** [Consensys/web3signer#898]
Confirm that Deneb changes made in web3signer are working with a CL/EL in a local network or devnet.

**Comment by non-fungible-nelson** [comment]
Reaching out to @barnabasbusa or @parithosh from the EF might be helpful in getting things tested. They may even be running Web3Signer on devnets now. Goerli won't be forked until November.

**Comment by barnabasbusa** [comment]
we are not currently testing web3signer but happy to allocate some validators if you guys want to start testing it on devnet 9/10.

**Comment by usmansaleem** [comment]
Tested on devnet 11 courtesy of Barnabas and parithosh. Blobsidecar signing seems to be working with Besu + Teku + Web3Signer integration. https://dora.dencun-devnet-11.ethpandaops.io/slot/7691
