### ISSUE TITLE
Let the user sign an arbitrary message with its keystore

### ISSUE THREAD

**Issue by Marketen** [Consensys/web3signer#976]
Currently, web3signer only permits signing certain types of data (as body payloads) in the `/api/v1/eth2/sign/{identifier}` ETH2 endpoint or  `/api/v1/eth1/sign/{identifier}` ETH1 endpoint. See https://consensys.github.io/web3signer/web3signer-eth2.html

It would be nice to add an endpoint (probably in ETH2 mode or both ETH1 & ETH2) that signs an arbitrary payload sent by the user. Something like:

```
"message": {
    "platform": "dappnode",
    "timestamp": "185921877",
    "pubkey":
    "0xaf294f5663defdba078e0c16b349952ab762f8019f42f45fc0a369666e12d836247e4d7a3e3bd564826dcffcfdc50114"
},
```

This is outside web3signer main scope, it would let users sign messages not necessarily related to the eth2 protocol

**Comment by pablomendezroyo** [comment]
To follow best practices and let others benefit from this approach and not only dappnode, how feasible would it be to add to the [standard](https://github.com/ethereum/remote-signing-api) a new type of signing to the [existing endpoint `/api/v1/eth2/sign/{identifier}`](https://ethereum.github.io/remote-signing-api/#/Signing/SIGN) to proof validation? something like `"type": "PROOF_OF_VALIDATION"`:

**Request**:
```json
{
  "type": "PROOF_OF_VALIDATION",
  "platform": "",
  "timestamp": "",
  "pubkey": "",
}
```

**Response**:
```json
  "message": {
    "platform": "",
    "timestamp": "",
    "pubkey": "",
  },
  "signature": ""
```

**Comment by pablomendezroyo** [comment]
@usmansaleem you right, it would be a simple signing
